rm -rf ./Build/Artifacts/TIF/*
rm -rf ./Build/Artifacts/QF/*
rm -rf ./Build/Artifacts/Standalone/*
rm -rf ./Build/Transpiled/TIF/*
rm -rf ./Build/Transpiled/QF/*
rm -rf ./Build/Transpiled/Standalone/*
rm -rf ./Build/Workspace/*
rm -rf ./Build/compile_log
rm -rf ./Build/error_log
